name: First CI Workflow

on: [push]

jobs:
    build-and-test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Install dependencies
            run: composer install  --prefer-dist --no-progress

          - name: Run a script
            run: echo "Hello, CI World"

          - name: Check PHP version
            run: php -v

          - name: Run PHPUnit
            run: vendor/bin/phpunit --bootstrap vendor/autoload.php tests